import TextSize from '@/types/TextSize';

export const TEXT_SIZES: TextSize[] = [
  'xlRegularNormal',
  'xlRegularNormalBold',
  'xlLowNormal',
  'xlLowBold',
  'xlMonoNormal',
  'xlMonoUppercase',
  'lgRegularNormal',
  'lgRegularNormalBold',
  'lgLowNormal',
  'lgLowBold',
  'lgMonoNormal',
  'lgMonoUppercase',
  'mdRegularNormal',
  'mdRegularNormalBold',
  'mdLowNormal',
  'mdLowBold',
  'mdMonoNormal',
  'mdMonoUppercase',
  'smRegularNormal',
  'smRegularNormalBold',
  'smLowNormal',
  'smLowBold',
  'smMonoNormal',
  'smMonoUppercase',
  'xsRegularNormal',
  'xsRegularNormalBold',
  'xsLowNormal',
  'xsLowBold',
  'xsMonoNormal',
  'xsMonoUppercase',
];
