name: Lint Commit Messages
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "export default {extends: [\"@commitlint/config-angular\"]};" > commitlint.config.mjs'
      - uses: wagoid/commitlint-github-action@v6
